### ISSUE TITLE
Summary Status is "skipped" although "assertionResult.status" is "passed"

### ISSUE THREAD

**Issue by jmeischner** [nvim-neotest/neotest-jest#35]
Dear haydenmeade, 

thank you for making this plugin 🙏. Unfortunately I have an issue with the status report in neotests summary window. I always get the status `skipped` although the test results output file is stating something different.
![CleanShot 2022-08-29 at 00 28 29@2x](https://user-images.githubusercontent.com/7792451/187097121-f21d014b-f7fb-4670-bc21-c574ac1d1af1.png)
![CleanShot 2022-08-29 at 00 19 44@2x](https://user-images.githubusercontent.com/7792451/187097065-f45669a7-4c27-4f5b-a975-687497023939.png)

 I get this behavior for different project setups (nx Monorepo & default Next.js application repo). I also added a log output here: https://github.com/haydenmeade/neotest-jest/blob/408245bec62813ed858de49ca07172d3f018a79f/lua/neotest-jest/init.lua#L248 which prints a `passed` status, so it seems the correct result is going through that procedure. I have no idea what leads to that behavior. I am even not sure if it's a neotest-jest or a neotest issue 🙈

Could you provide some guidance?

Thank you,
Jan

**Comment by codejunkienick** [comment]
I think I had the same issue. 
What helped for me is changing 
```              
require "neotest-jest" {
                jestCommand = "yarn test --",
```
to 
```              
require "neotest-jest" {
                jestCommand = "yarn test ",
```

**Comment by jmeischner** [comment]
Trank you @codejunkienick 

For me this issue magically disappeared in the meantime, most likely because I updated nvim and this plugin in the meantime 🤷‍♂️ but im not completely sure what I've done to fix it, because I haven't tried it for some time until today 🧙‍♀️🙈
