### ISSUE TITLE
Migrate repo to nvim-neotest?

### ISSUE THREAD

**Issue by stevearc** [nvim-neotest/neotest-jest#8]
The [nvim-neotest organization](https://github.com/nvim-neotest) has been created and the `neotest-go` adapter has already made its way over. Thoughts on migrating this adapter as well?

**Comment by primeapple** [comment]
Hey @haydenmeade , could we please do this? 

This would help getting PRs merged faster, since the possibility of finding maintainers will be higher. @rcarriga , could you give some insight of the process of transfering the repo?

**Comment by rcarriga** [comment]
Happy to migrate it :smile: I just need @haydenmeade to agree to the move. I can add you as maintainer and you'll maintain full control over the repo

**Comment by haydenmeade** [comment]
Happy to do this @rcarriga

**Comment by haydenmeade** [comment]
Migrated https://github.com/nvim-neotest/neotest-jest :tada:

**Comment by primeapple** [comment]
Thank you @haydenmeade for the big work you did here! You are awesome :)
